### ISSUE TITLE
Attack sound bug

### ISSUE THREAD

**Issue by itsschwer** [chameleonkid/Secrets#13]
#### Reproduce
Spam the attack input.

#### Expected behaviour
An attack sound plays every time the player attacks

#### Observed behaviour
Only one attack sound is played for as long as the attack input is spammed at a shorter interval than the length of the full attack

#### Potential cause
The sword attack sound seems to be played on awake, with the attack animation enabling/disabling the game object with the audio source. Inputting attack faster than the animation means that the audio source stays active, so it doesn't play its audio clip.

**Comment by chameleonkid** [comment]
Potential cause

The sword attack sound seems to be played on awake, with the attack animation enabling/disabling the game object with the audio source. Inputting attack faster than the animation means that the audio source stays active, so it doesn't play its audio clip.
Update:
-Issue is around even without PlayerSounds in the hierachy
-After some minutes of waiting the sounds is working again

**Comment by itsschwer** [comment]
Can confirm that all sounds stop working once some threshold is reached, could it be something to do with using `AudioSource.PlayOneShot` too many times?

I found a [thread](https://forum.unity.com/threads/overloading-with-audiosources-making-a-music-game.66460/) on what seems like the same issue from 2010, but it was left unanswered.

**Comment by itsschwer** [comment]
Potential cause: several sounds, including `attackSound1` and `attackSound2` seem to include a minute of silence.

**Comment by itsschwer** [comment]
The problem sounds all seem to be (mysteriously) 1:04 minutes long. I'll let you sort this out?

**Comment by chameleonkid** [comment]
Interesting.
Since all sounds are created by me I can confirm that I may be stupid... 
I always exported the same length which is pretty genius.
I'll cover this.

**Comment by chameleonkid** [comment]
Issue solved.
Except for chests.  That sounds has to be shortened.
