### ISSUE TITLE
Excessive round attack mana drain

### ISSUE THREAD

**Issue by itsschwer** [chameleonkid/Secrets#14]
The round attack coroutine's only yield instruction is `yield return null`, meaning that every other frame, the player will execute a round attack, decrementing mana. Ideally, the yield should be as long as the round attack animation.

**Comment by chameleonkid** [comment]
Since i dont have and roundattack-animation yet, we need to decided how to do this :)
AND
Does yield prevent the player from moving? If yes, thats not intended.

**Comment by itsschwer** [comment]
I think it's time to refactor the `Update` logic for the player

**Comment by chameleonkid** [comment]
ATM Roundattack is not planned to be in the game
