### ISSUE TITLE
Items on "explicit slots" dont trigger the SetupDescritption()

### ISSUE THREAD

**Issue by chameleonkid** [chameleonkid/Secrets#26]
When opening the Inventory and navigate to one of the explicit slots the item-description isnt changed from the last item that was in the general-inventory.

I can confirm the refresh is not triggered. 

![grafik](https://user-images.githubusercontent.com/70270710/102353980-2ef91c80-3faa-11eb-9842-6c9303502e24.png)

**Comment by itsschwer** [comment]
Should be fixed in commit 5d2c8de9

**Comment by chameleonkid** [comment]
Its fixed 5d2c8de
