### ISSUE TITLE
ButtonClick in Dialogue doesnt work with Joypad

### ISSUE THREAD

**Issue by chameleonkid** [chameleonkid/Secrets#27]
Seems like the "click" of Joypads doesnt trigger the OnClick() of the "Next"-Button.
Mouse is working as intended.

![grafik](https://user-images.githubusercontent.com/70270710/102378540-39291400-3fc6-11eb-9c28-d58c04c72a92.png)

**Comment by itsschwer** [comment]
From a brief test, it would appear that the input for starting the dialogue and progressing the dialogue are the same, causing the dialogue to restart instead of progressing. Mouse is exempt from this issue since the mouse click is not used to start the dialogue.

**Comment by itsschwer** [comment]
That actually might have been a separate issue. By default, the event system uses 'Submit' from the Input Manager to issue on click calls. In other words, the interact input has no effect because the event system is not listening for them.

**Comment by chameleonkid** [comment]
The IENumerator fixed this
