### ISSUE TITLE
Inventory Issues

### ISSUE THREAD

**Issue by chameleonkid** [chameleonkid/Secrets#33]
When receiving items sometimes theres an Index-Exception:
![grafik](https://user-images.githubusercontent.com/70270710/103171655-49ef4a80-484e-11eb-830c-400842dfca9d.png)

When Eqipping an Item the item stays in the Inventory and has and amount of 0:
![grafik](https://user-images.githubusercontent.com/70270710/103171671-67241900-484e-11eb-9713-775f11cec7da.png)

**Comment by itsschwer** [comment]
The second issue where the item stays in the item slots area with a count of 0 seems to only occur when it is the last item in the inventory. Working on a fix.

**Comment by itsschwer** [comment]
New PR (#34) should address at least the second part of this issue.

I'm unable to reproduce the first part so keep an eye out in case it reappears (hopefully in a consistent manner).

**Comment by chameleonkid** [comment]
Everything seems to be fixed.
