### ISSUE TITLE
Save/Load-Function not working anymore

### ISSUE THREAD

**Issue by chameleonkid** [chameleonkid/Secrets#35]
Recreationsteps:
Press Save/Load.

Error:
NullReferenceException: Object reference not set to an instance of an object
ES3Writer.Merge (ES3Reader reader) (at Assets/Plugins/Easy Save 3/Scripts/Writers/ES3Writer.cs:466)
ES3Writer.Merge () (at Assets/Plugins/Easy Save 3/Scripts/Writers/ES3Writer.cs:454)
ES3Writer.Save (System.Boolean overwriteKeys) (at Assets/Plugins/Easy Save 3/Scripts/Writers/ES3Writer.cs:480)
ES3Writer.Save () (at Assets/Plugins/Easy Save 3/Scripts/Writers/ES3Writer.cs:472)
ES3.Save[T] (System.String key, T value, ES3Settings settings) (at Assets/Plugins/Easy Save 3/Scripts/ES3.cs:107)
ES3.Save[T] (System.String key, T value) (at Assets/Plugins/Easy Save 3/Scripts/ES3.cs:67)
SimpleSave.SavePlayer () (at Assets/Scripts/GameManagers/SaveSystem/SimpleSave.cs:65)
SimpleSave.Save () (at Assets/Scripts/GameManagers/SaveSystem/SimpleSave.cs:28)
PauseManager.Save () (at Assets/Scripts/Menus/PauseManager.cs:38)
UnityEngine.Events.InvokableCall.Invoke () (at <e98ed0368295432e8c11e52d6243ee11>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <e98ed0368295432e8c11e52d6243ee11>:0)
UnityEngine.UI.Button.Press () (at C:/Program Files/Unity/Hub/Editor/2019.3.15f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Button.cs:68)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/Program Files/Unity/Hub/Editor/2019.3.15f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Button.cs:110)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/Program Files/Unity/Hub/Editor/2019.3.15f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at C:/Program Files/Unity/Hub/Editor/2019.3.15f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update() (at C:/Program Files/Unity/Hub/Editor/2019.3.15f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:377)

**Comment by chameleonkid** [comment]
Solved by deleting old save-files

**Comment by itsschwer** [comment]
Based on the error occurring at `ES3Writer.Merge` and this bit of documentation I found on [`ES3.Save`](https://docs.moodkie.com/easy-save-3/es3-api/es3-methods/es3-save/), I assume the error occurs when we want ES3 to save new data (most recently, player XP).

From what I understand, ES3 doesn't overwrite existing save files. Instead, it searches through an existing file and replaces existing keys with new values (*merging* the data). However, from what I can tell, it doesn't check if the key doesn't exist in the file when trying to merge, resulting in a null reference exception.

The workaround, as you've discovered, is to delete existing save files when the save structure is modified.

**Comment by itsschwer** [comment]
Loading was also affected by the rename of `FloatMeter` to `ConstrainedFloat`
