### ISSUE TITLE
Spellbooks need to be replaceable

### ISSUE THREAD

**Issue by chameleonkid** [chameleonkid/Secrets#69]
Since there are now 3 SpellBookSlots, Spellbooks need to be swapable/replaceable.

My Idea is to ask for Slot1/2/3 when clicking a spellbook.
This would mean, to have a special slot for spellbooks i guess.

In Detail:

You got nothing in your inventory yet, but 1 Spellbook and you already got 3 Spellbooks equipped.
I.E.:

EquipSlot1 = IceBook 
EquipSlot2 = FireBook 
EquipSlot3 = LightBook
InventorySlot = ShrinkBook.

You click that Spellbook and you'll get 3 Buttons which ask for the Slot. (Might be a small Panel)
Depending on the button you press the book gets swapped with the one in Slot 1/2/3.
Lets say you press 1.

You will swap now the Icebook into the Inventory and the ShrinkBook into slot 1.

I think this would be the easiest way.

**Comment by itsschwer** [comment]
## New suggestion
Implement item unequipping instead.
- When trying to equip a spell, check for each slot to see if it's free.
    - If there's a free slot, equip the spell there.
    - Else simply replace the last slot (to reduce inventory management friction)

### Reasoning
- The player currently has no way to unequip items.
- This implementation would avoid dealing with an additional submenu and associated input challenges.

**Comment by chameleonkid** [comment]
Special thanks to @itsschwer who once again solved everything I struggled with.
